# Generated by Django 2.1.4 on 2019-02-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0002_auto_20190212_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='engine_cubic_centimeters',
            new_name='cubic_centimeters',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='engine_manufacturer',
            new_name='manufacturer',
        ),
    ]
