# Generated by Django 2.1.4 on 2018-12-11 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0002_auto_20181211_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 23, 3, 20, 268279)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 23, 3, 20, 267878)),
        ),
    ]
