# Generated by Django 2.1.4 on 2018-12-11 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0003_auto_20181211_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 23, 13, 19, 194534)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 23, 13, 19, 194134)),
        ),
    ]
