# Generated by Django 2.1.4 on 2019-02-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0003_auto_20190221_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
    ]
