# Generated by Django 2.1.4 on 2018-12-11 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0005_auto_20181211_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 23, 20, 53, 31391)),
        ),
    ]
