# Generated by Django 2.1.4 on 2018-12-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0007_auto_20181211_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bundles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='excursions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='exhibitions',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
