# Generated by Django 2.1.4 on 2018-12-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0009_auto_20181211_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
