# Generated by Django 2.1.4 on 2018-12-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0010_auto_20181211_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='Comment'),
        ),
    ]
