# Generated by Django 2.1.4 on 2018-12-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0011_comment_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='excursion',
        ),
        migrations.AddField(
            model_name='bundle',
            name='excursions',
            field=models.ManyToManyField(blank=True, null=True, to='cartrip.Excursion'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='exhibitions',
            field=models.ManyToManyField(blank=True, null=True, to='cartrip.Exhibition'),
        ),
    ]
