# Generated by Django 2.1.4 on 2018-12-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0012_auto_20181212_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartrip.Engine'),
        ),
    ]
