# Generated by Django 2.1.4 on 2018-12-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0013_auto_20181212_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
