# Generated by Django 2.1.4 on 2019-01-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrip', '0014_excursion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
